// File generated by FlutterFire CLI.
// This file is automatically created to store Firebase configuration for different platforms (Web, Android, iOS, etc).

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// DefaultFirebaseOptions
// This class provides the correct Firebase configuration depending on the platform the app is running on.
// Instead of manually selecting configs, the app calls:
// DefaultFirebaseOptions.currentPlatform and this class returns the correct one automatically.
class DefaultFirebaseOptions {
  // Returns the FirebaseOptions for the current platform.
  // This is used during Firebase.initializeApp(...) to connect the app to the correct Firebase project settings.
  static FirebaseOptions get currentPlatform {

    // Special case for  Web, it uses a different initialization method and must be handled first.
    if (kIsWeb) {
      return web;
    }

    // For non-web platforms, determine based on OS
    switch (defaultTargetPlatform) {

      // Android device or emulator
      case TargetPlatform.android:
        return android;

      // iOS device or simulator
      case TargetPlatform.iOS:
        return ios;

      // macOS desktop app
      case TargetPlatform.macOS:
        return macos;

      // Windows desktop app
      case TargetPlatform.windows:
        return windows;

      // Linux is not configured in this project
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux.',
        );

      // Any unsupported or unknown platform
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // Web Firebase configuration
  // Contains all required keys to connect the web app to Firebase
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHrtK2JhrHa1jDWJ5bQ8ixnozAJR7TCGs',
    appId: '1:17311803750:web:5130aab3442f32a32040a7',
    messagingSenderId: '17311803750',
    projectId: 'safe-home-monitor',
    authDomain: 'safe-home-monitor.firebaseapp.com',
    storageBucket: 'safe-home-monitor.firebasestorage.app',
    measurementId: 'G-NV63PMPEK9',
    databaseURL: 'https://safe-home-monitor-default-rtdb.firebaseio.com',
  );

  // Android Firebase configuration
  // Used when running the app on Android devices.
  // Does not include authDomain or measurementId because they are not required.
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMqKK5ZQ4GGR2XvfXeEZjteMp0_w_iZ_k',
    appId: '1:17311803750:android:82777259ca4f47e02040a7',
    messagingSenderId: '17311803750',
    projectId: 'safe-home-monitor',
    storageBucket: 'safe-home-monitor.firebasestorage.app',
    databaseURL: 'https://safe-home-monitor-default-rtdb.firebaseio.com',
  );

  // iOS Firebase configuration
  // Includes iosBundleId which identifies the app on iOS.
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbhcNqGQvJqIjnrN11ll9yQKK1YbpONUE',
    appId: '1:17311803750:ios:123ba0f0d373c75d2040a7',
    messagingSenderId: '17311803750',
    projectId: 'safe-home-monitor',
    storageBucket: 'safe-home-monitor.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
    databaseURL: 'https://safe-home-monitor-default-rtdb.firebaseio.com',
  );

  // macOS Firebase configuration
  // Similar to iOS because both use Apple ecosystem settings.
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbhcNqGQvJqIjnrN11ll9yQKK1YbpONUE',
    appId: '1:17311803750:ios:123ba0f0d373c75d2040a7',
    messagingSenderId: '17311803750',
    projectId: 'safe-home-monitor',
    storageBucket: 'safe-home-monitor.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
    databaseURL: 'https://safe-home-monitor-default-rtdb.firebaseio.com',
  );

  // Windows Firebase configuration
  // Uses web-like configuration because Windows apps, rely on web-based Firebase services.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHrtK2JhrHa1jDWJ5bQ8ixnozAJR7TCGs',
    appId: '1:17311803750:web:6399617e919c1c852040a7',
    messagingSenderId: '17311803750',
    projectId: 'safe-home-monitor',
    authDomain: 'safe-home-monitor.firebaseapp.com',
    storageBucket: 'safe-home-monitor.firebasestorage.app',
    measurementId: 'G-SZY59WGWE8',
    databaseURL: 'https://safe-home-monitor-default-rtdb.firebaseio.com',
  );
}