import 'dart:async';

import 'package:firebase_auth/firebase_auth.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/material.dart';

import 'firebase_options.dart';
import 'screens/login_screen.dart';
import 'screens/main_shell.dart';

// Main entry point of the application.
// This runs before any widget is shown and is responsible for: making sure Flutter is initialized, initializing Firebase, starting the app
Future<void> main() async {
  // Ensures Flutter engine bindings are ready before calling async setup code like Firebase.initializeApp().
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase using the platform-specific configuration generated by FlutterFire.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Start the root widget of the app.
  runApp(const SafeHomeApp());
}

// Root widget of the Safe Home Monitor app.
// This defines the global MaterialApp configuration
class SafeHomeApp extends StatelessWidget {
  const SafeHomeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      // Removes the debug banner in development mode.
      debugShowCheckedModeBanner: false,

      // Title used by the operating system / task switcher where applicable.
      title: 'Safe Home Monitor',

      // Global theme for the entire application.
      theme: ThemeData(
        brightness: Brightness.light,
        scaffoldBackgroundColor: Colors.white,

        // Main accent color used in the app.
        primaryColor: const Color(0xFF4A90E2),

        // Builds a complete color scheme starting from the app’s main blue.
        colorScheme: ColorScheme.fromSeed(
          seedColor: const Color(0xFF4A90E2),
        ),
      ),

      // First screen shown when the app launches.
      home: const SplashScreen(),
    );
  }
}

// Splash screen shown when the app opens.
// This screen: plays a fade animation, waits briefly, checks whether the user is already logged in, navigates to either MainShell or LoginScreen
class SplashScreen extends StatefulWidget {
  const SplashScreen({super.key});

  @override
  State<SplashScreen> createState() => _SplashScreenState();
}

// State class for the animated splash screen.
// SingleTickerProviderStateMixin is used because this screen owns one AnimationController.
class _SplashScreenState extends State<SplashScreen>
    with SingleTickerProviderStateMixin {
  // Controls the splash animation timing.
  late final AnimationController _controller;

  // Fade animation used to smoothly show the logo and title.
  late final Animation<double> _fadeAnimation;

  @override
  void initState() {
    super.initState();

    // Create the animation controller for the splash fade effect.
    _controller = AnimationController(
      vsync: this,
      duration: const Duration(milliseconds: 1200),
    );

    // Create a curved animation so the fade feels smoother than a plain linear transition.
    _fadeAnimation = CurvedAnimation(
      parent: _controller,
      curve: Curves.easeInOut,
    );

    // Start the fade animation immediately when the screen appears.
    _controller.forward();

    // Keep the splash screen visible for 2 seconds, then decide where to navigate next.
    Timer(const Duration(seconds: 2), () {
      /// Prevent navigation if the widget was already removed.
      if (!mounted) return;

      // Read the currently signed-in Firebase user.
      // If not null, the app will open the main shell directly.
      final currentUser = FirebaseAuth.instance.currentUser;

      // Replace the splash screen with the next page using a custom fade transition.
      Navigator.of(context).pushReplacement(
        PageRouteBuilder(
          transitionDuration: const Duration(milliseconds: 900),

          // Choose destination based on login state.
          pageBuilder: (_, animation, __) =>
              currentUser != null ? const MainShell() : const LoginScreen(),

          // Fade the next screen in.
          transitionsBuilder: (_, animation, __, child) {
            return FadeTransition(
              opacity: animation,
              child: child,
            );
          },
        ),
      );
    });
  }

  @override
  void dispose() {
    // Dispose the animation controller to avoid memory leaks.
    _controller.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      // Dark navy splash background matching app branding.
      backgroundColor: const Color(0xFF0D1B2A),

      body: Center(
        // FadeTransition applies the animation created in initState()
        // to the logo and title.
        child: FadeTransition(
          opacity: _fadeAnimation,
          child: Column(
            mainAxisAlignment: MainAxisAlignment.center,
            children: const [
              // Main splash icon / logo.
              Icon(
                Icons.shield_outlined,
                size: 110,
                color: Colors.white,
              ),

              SizedBox(height: 20),

              // App title shown under the icon.
              Text(
                'Safe Home Monitor',
                style: TextStyle(
                  color: Colors.white,
                  fontSize: 28,
                  fontWeight: FontWeight.w600,
                  letterSpacing: 0.5,
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}